### ISSUE TITLE
Information regarding project selection

### ISSUE THREAD

**Issue by AliAyub007** [TensorFlowKR/dlcampjeju#1]
Hello, 
      Can I apply with any project i.e If I want to work on epilepsy related machine learning project so can I apply for this?

**Comment by hunkim** [comment]
Basically, it's not limited. However, you need a very interesting and strong proposal. Good luck!

**Comment by AliAyub007** [comment]
Oh got it! Thanks for the information.

**Comment by tarvos21** [comment]
@AliAyub007, I am also quite interested in epilepsy related machine learning, what may your project look like, predicting seizures?  Might it be possible to join your project? I have the idea of predicting seizures according to data of EEG, blood pressure, heartbeat, food, weight, sleeping hours and etc, but not very clear yet.

**Comment by ragulpr** [comment]
@AliAyub007 @tarvos21  Seizure prediction could definitely fit into my project too so if we all make it there's room for collaboration!

If we're talking the kind of after-the-fact prediction of the Kaggle-competition it's a little bit complex though

**Comment by tarvos21** [comment]
@ragulpr oh, I have submitted one application about seizure prediction, but I don't know the filtering results yet, I have read some materials of the seizure prediction competition 2 years ago on Kaggle, it seems interesting. If your application passes, I am happy to help!

**Comment by ragulpr** [comment]
Awesome, my application is algo-centric not data centric so we'll see! Thanks and good luck!
