### ISSUE TITLE
Is it possible for a team of 2 people apply for only one funding?

### ISSUE THREAD

**Issue by QuantML** [TensorFlowKR/dlcampjeju#10]
Hi, I know someone asked this kind of questions about applying as a team before. However, I am not sure if this one is the same case. My question is in the case of if we apply as a team of 2 people but for only 1 funding, is it possible? As we work a a team so it would be much more benefits if we can work together.

Thank you.

**Comment by hunkim** [comment]
We encourage each participant work alone. Any specific reason that you want
to work as a team?

**Comment by QuantML** [comment]
Thank you for your quick answer. The reason we want to work as a team is because the proposal we are going to propose is a part of our project that we have been working on it together for over a year and we aim to corporate deep learning to that project. We would be very much appreciated if you could consider our case. Thank you very much.
