### ISSUE TITLE
Can I join as a team?

### ISSUE THREAD

**Issue by kyoseoksong** [TensorFlowKR/dlcampjeju#2]
Thanks for holding such a great event!
I'd like to know if I can apply as a small team which consists of 2 members. 
Thanks in advance.

**Comment by hunkim** [comment]
Thanks for the question. 2 members can apply separately, but usually it's individual work. Also, there is no guarantee that both of you can be accepted. Good luck!

**Comment by kyoseoksong** [comment]
I got it! Thanks for the quick response. :)

**Comment by ltnanitya** [comment]
i'm working in Internet of Things, wireless networks area. I do not have previous experience about ML, but i want to learn it for my future project. So, how can I join the campus?
Best regard.

**Comment by hunkim** [comment]
This is not a learning camp. I think you need a strong background.

**Comment by ltnanitya** [comment]
Thank you!
