### ISSUE TITLE
Questions on weekend program

### ISSUE THREAD

**Issue by Junyoungpark** [TensorFlowKR/dlcampjeju#21]
In qualification section, there is a mention that
 "Must be able to stay in Jeju Island from July 3rd to 28th. (Weekday camp programs run from 10AM to 5PM)"

Then, do you have Weekend program also?

**Comment by hunkim** [comment]
We may have some weekend activities, but they are optional.

Sung

**Comment by Junyoungpark** [comment]
Thanks a lot :)
