### ISSUE TITLE
Can we send our LoR some time even after the deadline of 11:59 pm AOE ?

### ISSUE THREAD

**Issue by rishabh135** [TensorFlowKR/dlcampjeju#28]
@hunkim As I came to know about this camp today only , can I please request you to extend the deadline for submission of LoR from my professor a few days ? Also can you please specify the best way to send you the LoR , will a mail be fine ?
Best of luck for this initiative , looks supremely cool to code new things while interacting with some of the best minds behind tensorflow .

**Comment by hunkim** [comment]
Unfortunately, no extension. However, still, you have  more than 12 hours.
(Deadline April 20: 11:59 PM AOE). Good luck!
