### ISSUE TITLE
Resuls

### ISSUE THREAD

**Issue by Seleucia** [TensorFlowKR/dlcampjeju#29]
Hello, 
I applied to another summer school and got accepted, and I must make payment before the end of this month for this conference. In case of admission for the MLJejuCamp, I prefer this one. Would it possible to learn if I'm get accepted or rejected for MLJejuCamp before end of this month?

**Comment by hunkim** [comment]
Dear Seleucia,

We will notify results on May 10 as scheduled.

Cheers,
Sung
