### ISSUE TITLE
Do I retain the IP rights to whatever I produce during the time in the ML Camp?

### ISSUE THREAD

**Issue by KyotoSunshine** [TensorFlowKR/dlcampjeju#3]
Do I retain the IP rights to whatever I produce during the time in the ML Camp?
Is some kind of contract going to be signed by the people who attend the camp?

**Comment by hunkim** [comment]
Nope. It's all yours as long as you can release the work in github.

**Comment by KyotoSunshine** [comment]
Being able to release the code publicly on github is a requirement to being able to participate in the camp?

**Comment by hunkim** [comment]
Yes.

**Comment by hunkim** [comment]
Since others might be interested, let it open.
