### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by itsss** [TensorFlowKR/dlcampjeju#30]
The results will be announce to website? or e-mail ??? (May 10)

**Comment by hunkim** [comment]
Will be emailed.

**Comment by harishanand95** [comment]
@hunkim Would it be better to have the selected candidates list and their proposals be made available in this repo on May 10?

**Comment by hunkim** [comment]
Sure. We will think/discuss about it.

Sung

**Comment by Seleucia** [comment]
Is it possible to see how many people applied for the camp?

**Comment by itsss** [comment]
what time(ex. 4 PM) the results will be announce to e-mail? (May 10)

**Comment by hunkim** [comment]
We are finalizing the results. It would be within May 10 AoE.

Sung

**Comment by ayehninnkhine** [comment]
Have results been announced?
