### ISSUE TITLE
Result

### ISSUE THREAD

**Issue by ayehninnkhine** [TensorFlowKR/dlcampjeju#32]
Have the results been announced?

**Comment by hunkim** [comment]
Not yet. It will be before May 10 11:59 PM AoE.

**Comment by chg0901** [comment]
Haha, Hoping I can win this opportunity to get the help of Google's engineers and learn more about using TF and applying it to the Computer Network.

**Comment by jingjing-gong** [comment]
Will all applicants be notified? Or only accepted applicants will be notified?

**Comment by ayehninnkhine** [comment]
any update?
Finish announcing selected participants?

**Comment by jjmstars** [comment]
Not yet? Im just curious about the result

**Comment by itsss** [comment]
NOT YET? what time(ex. 4 PM) the results will be announce to e-mail?
