### ISSUE TITLE
result

### ISSUE THREAD

**Issue by michaelhzj** [TensorFlowKR/dlcampjeju#36]
Has passed on May 10  but  i haven't recieve any email  about that

**Comment by shubham0704** [comment]
It's still May 10 according to AOE time check  https://time.is/Anywhere_on_Earth

**Comment by justanotherminh** [comment]
Nevertheless they shouldn't wait until the very last minute.

**Comment by hunkim** [comment]
It will be out very shortly.

**Comment by Rohankhameshra** [comment]
@hunkim,
When you announce results, can you please send mails ​to both selected and non selected people also upload a list of people here on git, to make it clear for everybody.

**Comment by M4t1ss** [comment]
FYI, the results are out

**Comment by wanghaoLisa** [comment]
I didn't receive the results email, does that mean I am not selected?

**Comment by chg0901** [comment]
I am out and I received the inform email. Be patient.

**Comment by juditacs** [comment]
Gmail flagged it as Promotion for me, maybe it's there.

**Comment by ayehninnkhine** [comment]
Gmail flagged it as promotion. 
Find there.

**Comment by luongminh97** [comment]
Found it in the promotions.Rekt
