### ISSUE TITLE
Selected candidates list and their proposals

### ISSUE THREAD

**Issue by Seleucia** [TensorFlowKR/dlcampjeju#39]
When will selected candidates list and their proposals be publicly available?

Best

**Comment by unnir** [comment]
sure, check the git

sorry, I mean the PR

https://github.com/TensorFlowKR/MLJejuCamp/pull/38/commits/2af8919cb9b4e5c16342af60d5054389a29fc96a

**Comment by hunkim** [comment]
Now it's in the main: [Participant List](../blob/master/Participants.md)
