### ISSUE TITLE
What is the main content of this seminar? The schedule

### ISSUE THREAD

**Issue by HannaRiver** [TensorFlowKR/dlcampjeju#43]
I want to join this camp very much, though i gotten the reject email. So i want to go to jeju by myself. 
What is the main content of this camp? Only the knowledge about TF? And different term have different mentor？ Can we join these term? BTW , Can i booking the dormitory of Jeju National University?

**Comment by unnir** [comment]
Persistence is a great quality, good luck 👍

**Comment by ljm861** [comment]
Sorry for the late reply. 
1) Main content: To develop participants' own projects with assistance from their mentors for a month
2) This camp requires not only for the knowledge about TF, but also the knowledge about machine learning and deep learning.
3) We have 20 participants and each participant has their own mentor.
4) Unfortunately you cannot join the camp at the moment.
5) It's not available to book the dormitory of JNU.

Thank you and have a great day! :)
