### ISSUE TITLE
HI I will participate in second-leaning camp

### ISSUE THREAD

**Issue by jhstyle49** [TensorFlowKR/dlcampjeju#46]
Hello, I will participate in second- leaning camp.(7/25)
also I'm interested in Master's degree  at HKUST.
so when i participate in second-leaning camp at jeju, I want to meet hunkim professor at HKUST for master's degree if it's possible.
please call me back to jhstyle49@gmail.com

**Comment by hunkim** [comment]
For hkust, please send a cv to sung kim hunkim@gmail.com

**Comment by jhstyle49** [comment]
Actually, I didn't send cv yet because I didn't ready cv and tofle.
but I already sent e-mail about me.
before I decide to quit my job and study tofle score, I want to meet you.
please one more check my e-mail from jhstye49@gmail.com.
