### ISSUE TITLE
Add /favicon.ico

### ISSUE THREAD

**Issue by e9t** [TensorFlowKR/dlcampjeju#48]

**Comment by kkweon** [comment]
@ljm861 이거 보니까 떠올랐는데 그룹(TFKR) 로고 파일 가지고 계신가요?
그때 기호님으로부터 받은 건 기억하는데 저는 그때 백업을 안해놔서 :cry: 
여기에 assets에 백업 할겸 겸사 겸사 하면 좋을 것 같습니다.

**Comment by kkweon** [comment]
TF Logo svg
https://drive.google.com/open?id=0B1ay5kXWGF_9Tld0eGFxV2xiM28

**Comment by e9t** [comment]
Thanks @kkweon! Just converted an SVG to a favicon and added it to the `dev-2018` branch!
https://github.com/TensorFlowKR/mlcampjeju/commit/f282d4fb2e4aa897217800cb362a0a7998a78185
