### ISSUE TITLE
Add application related info

### ISSUE THREAD

**Issue by e9t** [TensorFlowKR/dlcampjeju#53]
cc: @hwalsuklee

**Comment by hwalsuklee** [comment]
*Link : https://docs.google.com/forms/d/1wzqsuQgI8YF4rsZplnNSPltxmag6wwbMWO07BInKbts/edit
Please contact me if you want to edit it. (hwalsuk.lee@gmail.com)

*Preview : https://docs.google.com/forms/d/e/1FAIpQLSf7eGrKlxWnhq0FFdqJSkMpU2XxQjvxKyXMKq7WzZFNvVaAmg/formResponse

**Comment by e9t** [comment]
@hwalsuklee Once the form is ready, I think the following section can be filled out, and we'll be ready to ship!
https://github.com/TensorFlowKR/dlcampjeju/blob/master/2018/index.md#how-to-apply
