### ISSUE TITLE
[discussion] Countdown might confuse people

### ISSUE THREAD

**Issue by kkweon** [TensorFlowKR/dlcampjeju#58]
![image](https://user-images.githubusercontent.com/2981167/38602030-67c0b1d6-3d1e-11e8-9a31-5aa0291ffc0b.png)

I think we can do one of these:

- Remove the countdown
- Add a help label for the countdown
- Add both countdown (application and camp starting date)
- leave it as is

**Comment by e9t** [comment]
I'd say we go for the second option, for example:

"Timedelta untill gathering at Jeju:"

**Comment by e9t** [comment]
Resolved by #59
