### ISSUE TITLE
What qualifies as 'open source'?

### ISSUE THREAD

**Issue by juneoh** [TensorFlowKR/dlcampjeju#6]
The application section states that all applicants are required to "Release the code on the github as Open Source". What level of 'Open Source' are the participants expected to meet? For instance—

- Is there a pool of license for the participants to choose from, such as MIT, GPL, or the public domain?
- A public repository on GitHub without explicitly designated license defaults to "all rights reserved". Does this qualify as releasing Open Source?
- Some open source projects GPL their code, and require a purchase of license for extended commercial use. Is such excercise of copyright valid for the results of this camp?
- Can the participants link external organizations, e.g. project teams or commercial companies, on the repository of the product code?

Furthermore, on a related note—

- A project cannot be said to adhere to the philosophy of open source if without proper documentation. Are the participants expected to provide detailed documentation along with the finished code, within the duration of the camp?

**Comment by hunkim** [comment]
Thanks for excellent questions!

Open source with any license is OK.

"Can the participants link external organizations, e.g. project teams or
commercial companies, on the repository of the product code?" requires
further discussion, but we are very flexible.


"without proper documentation." We don't care too much for documentation at
this time.
