### ISSUE TITLE
extending of the application deadline

### ISSUE THREAD

**Issue by ghost** [TensorFlowKR/dlcampjeju#60]
Sir/Madam, i got to know about this camp today only from my friend. i have an interesting topic using computer vision algorithms like cnn etc that i wish to implement as a research paper but lack the resources to do so. i really wish if you could allow me to submit my proposal. if you wish to contact me you can mail me at nithin.varghese1357@gmail.com
Thank you.

with regards,
Nithin Varghese
(deep learning enthusiast)

**Comment by unnir** [comment]
> Applications will be accepted until April 30th, 2018.

**Comment by e9t** [comment]
@nithin1357, please follow the directions in the link below:
http://jeju.dlcamp.org/2018/#how-to-apply
