### ISSUE TITLE
What kind of guidance can a student expect (and not expect) from mentors at the camp?

### ISSUE THREAD

**Issue by mngrwl** [TensorFlowKR/dlcampjeju#7]
For example, will they mainly just help us with implementing our models in Tensorflow, or they could help us design the model with new deep learning concepts, help us create a better pipeline for data preprocessing etc?

**Comment by hunkim** [comment]
All of them hopefully. :-)

**Comment by mngrwl** [comment]
@hunkim thank you, professor. 🥇
