### ISSUE TITLE
Can we propose more than one project?

### ISSUE THREAD

**Issue by mngrwl** [TensorFlowKR/dlcampjeju#8]
If I have two different ideas but am having difficulty choosing, can I apply with both proposals and you can select one for me? This is because I wouldn't want to be rejected just because one of my ideas wasn't unique/interesting enough for the camp. :)

**Comment by hunkim** [comment]
Try to write both ideas.

**Comment by mngrwl** [comment]
@hunkim that would be awesome, thanks a lot!
